name: adder
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.adder
        pluginClass: AdderPlugin
      ios:
        pluginClass: AdderPlugin
      windows:
        pluginClass: AdderPlugin
